## High-Performance Computing with NumPy

**Course:** EE6201 – Power Systems Lab | **Instructor:** V. Seshadri Sravan Kumar | **IIT Hyderabad** 

This notebook introduces **NumPy **(Numerical Python), the fundamental package for scientific computing. Some examples in this notebook are **adopted or adapted from publicly available resources**.

---

### Advantages of NumPy

Standard Python lists are versatile but slow for heavy mathematical lifting. NumPy introduces the ndarray (n-dimensional array), which offers several critical advantages:

**Homogeneity:** Unlike lists, all elements in a NumPy array must be of the same type (typically float or int). This allows the computer to store data in a continuous block of memory.

**Vectorization & Performance:** NumPy operations are implemented in C under the hood, allowing for "vectorized" operations that avoid the overhead of Python loops.

**Advanced Indexing:** It supports complex slicing, boolean masking, and multi-dimensional indexing.

**Memory Efficiency:** NumPy arrays consume significantly less memory compared to Python lists.


**Importing the library:** To use NumPy, we must first import the library. The standard convention in the scientific community is to alias it as `np`.

In [2]:
import numpy as np

### Measuring Speed with `%timeit`

To prove NumPy's efficiency, we use the `%timeit` command in Jupyter. It runs a statement multiple times to provide an accurate average execution time.

**Syntax**:
```python
%timeit [operation_to_test]
```

##### Exercise 1: The NumPy Speed Test

In this exercise, we will compare the time taken to square a large set of integers (representing perhaps a vector of current values $I$) using a standard Python list versus a NumPy array.

**Task:**
1. Define a variable $N = 1,000,000$.
2. Create a standard Python list containing integers from $0$ to $N-1$.
3. Create a NumPy array from that same range.
4. Square every element in the list using a for loop and measure the time.
5. Square every element in the NumPy array using vectorization and measure the time.

In [11]:
# Step 1: Define N
N = 1000000

# Step 2: Create a Python list using range
python_list = None  # Remove none and fill 

# Step 3: Create a NumPy array
numpy_array = None  # Remove none and fill

print(f"Testing performance for N = {N} elements...")

# --- Test Python List Performance ---
print("Python List (Square operation):")
# %timeit  # Fill it 

# --- Test NumPy Performance ---
print("\nNumPy Array (Square operation):")
# %timeit  # Fill it

Testing performance for N = 1000000 elements...
Python List (Square operation):

NumPy Array (Square operation):


---
### The NumPy ndarray Core Object

The primary building block of NumPy is the ndarray (N-dimensional array). It is a multidimensional container of items of the same type and size.
1. 1D Array: Think of this as a Vector (e.g., a list of bus voltages).
2. 2D Array: Think of this as a Matrix (e.g., an Admittance Matrix $Y_{bus}$).
3. 3D Array: A stack of matrices. While harder to visualize, think of it as a time-series of $Y_{bus}$ matrices where each "slice" is the state of the grid at a different second.

#### Attributes of an ndarray
Every NumPy object carries specific properties that describe its structure and data type.

| Attribute | Explanation | Syntax |
|-----------|------------|--------|
| ndim | The number of axes (dimensions) of the array. | `array.ndim` |
| shape | A tuple indicating the size of the array in each dimension (Rows, Columns). | `array.shape` |
| size | The total number of elements in the array. | `array.size` |
| dtype | The data type of the elements (e.g., int64, float64, complex128). | `array.dtype` |

---
### Array Creation Methods

There are five primary ways to generate arrays in NumPy:

1. **From Existing Data**: Convert Python lists or tuples into NumPy arrays.
**Syntax:**
```python
np.array([1, 2, 3])
np.array([[1, 2], [3, 4]])
```
* Automatically infers data type unless specified using `dtype=`
* Can create 1D, 2D, or higher-dimensional arrays
2. **Numerical Ranges**
* `np.arange(start, stop, step)`: Similar to Python's `range()`. Stop value is excluded.
```python
np.arange(0, 10, 2)
```
* `np.linspace(start, stop, num)`: Generates `num` evenly spaced values. Stop is included by default.
```python
np.linspace(0, 1, 5)
```
* `np.logspace(start, stop, num)`: Generates values evenly spaced on a logarithmic scale.
```python
np.logspace(0, 3, 4)
```
3. **Placeholders and Constant Arrays**:

* `np.zeros(shape)`:  Array filled with 0s
* `np.ones(shape)`:  Array filled with 1s
* `np.full(shape, value)`: Array filled with a specific value
* `np.empty(shape)`: Uninitialized array (may contain arbitrary memory values)
```python
np.zeros((2, 3))
np.full((3, 3), 7)
```
4. **Specialized and Identity Matrices**
* `np.eye(N)`: Creates an identity matrix of size `N x N`.
```python
np.eye(3)
```
* `np.diag(v, k=0)`
  If `v` is 1D → creates diagonal matrix
  If `v` is 2D → extracts diagonal elements. `k=1` for upper diagonal, `k=-1` for lower diagonal
```python
np.diag([1, 2, 3])
```

##### Substation Data Initialization

***Example 2:*** You are setting up the data for a 3-bus network. You need to initialize the Admittance Matrix ($Y_{bus}$) and a vector for the target voltages.

*Task:* 
1. Create a $3 \times 3$ Identity Matrix representing the base connections.
2. Create a $3 \times 1$ Column Vector of ones representing the initial guess for Bus Voltages (1.0 pu).
3. Create a diagonal matrix using the list [0.5, 0.2, 0.8] representing the shunt reactor values.
4. Extract the diagonal of the matrix created in Step 1.

In [10]:
# Step 1: Create 3x3 Identity Matrix
Y = ...

# Step 2: Create a 3-element vector of 1.0 (Voltages)
v_0 = ...

# Step 3: Create a diagonal matrix from reactor_list
reactor_list = [0.5, 0.2, 0.8]
shunt_matrix = ...

# Step 4: Extract the diagonal from identity_Y
diag_elements = ...

print("Identity Matrix:\n", Y)
print("\nVoltage Vector:\n", v_0)
print("\nShunt Matrix:\n", shunt_matrix)
print("\nExtracted Diagonal:", diag_elements)

Identity Matrix:
 Ellipsis

Voltage Vector:
 Ellipsis

Shunt Matrix:
 Ellipsis

Extracted Diagonal: Ellipsis


---
### Reshaping Arrays

In Power Systems, you might receive a flat stream of 12 PMU measurements and need to reshape them into a $4 \times 3$ matrix (representing 4 buses with 3-phase readings). 

`np.reshape()`: The `reshape()` function allows you to change the dimensions of an array without changing its data.

**Syntax:** `np.reshape(array, (new_rows, new_cols))`

**Important:** Views vs. Copies: By default, reshape returns a view of the original data. This means the two variables point to the same location in memory. If you modify the reshaped array, the original array will also change. To prevent this, always use the `.copy()` method if you need an independent matrix.

**Reshaping with -1**: If you are unsure of one of the dimensions, you can use -1. NumPy will automatically calculate the correct value for that dimension based on the total number of elements.

Example: If you have 10 elements and reshape to (2, -1), NumPy calculates the required second dimension to be 5.

**Example 3: PMU Data Formatting:** You have received a flat sequence of 12 current measurements from a substation. You need to organize these into a matrix where each row represents a specific Bus, and each column represents a Phase (Phase A, B, and C).

*Task:*
1. Create a 1D array called raw_data containing numbers from 1 to 12.
2. Reshape raw_data into a $4 \times 3$ matrix called pmu_matrix.
3. Use the `.copy()` method to create a separate matrix called safe_matrix.
4. Modify an element in safe_matrix and observe that raw_data remains unchanged.
5. Practice the -1 functionality by reshaping raw_data into 6 rows and an automated number of columns.

In [9]:
# Step 1: Create flat data (1 to 12)
raw_data = np.arange(1, 13)

# Step 2: Reshape into 4 Buses and 3 Phases
# Note: This is a "view"
pmu_matrix = ... 

# Step 3: Create an independent copy
safe_matrix = ...

# Step 4: Modify safe_matrix (e.g., set first element to 99)
# safe_matrix[0, 0] = 99
# Check if raw_data[0] is still 1

# Step 5: Use -1 to create 6 rows automatically
auto_matrix = ...

print("Original Data:\n", raw_data)
print("\nPMU Matrix (4x3):\n", pmu_matrix)
print("\nAuto-calculated Matrix (6x?):\n", auto_matrix)

Original Data:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

PMU Matrix (4x3):
 Ellipsis

Auto-calculated Matrix (6x?):
 Ellipsis


---
### Accessing Elements: Indexing and Slicing

There are three primary ways to access or modify data within a NumPy array.

1. **Basic Indexing and Slicing (1D & 2D):** Indexing in NumPy starts at 0.

* 1D Arrays: Accessing elements is similar to Python lists (x[index]).
* 2D Arrays: Instead of x[row][col], NumPy uses the more efficient comma-separated syntax: x[row, col].

**Negative Indexing:** Use negative numbers to count from the end (-1 is the last element).

**Slicing and Striding:** The syntax is `start:stop:step`.

`x[1:5]:` Elements from index 1 to 4.

`x[::2]:` Every second element (useful for skipping phases or taking every other sample).

**2D Slicing:** You can slice rows and columns simultaneously.

`x[:, 0]:` Extracts the first column (e.g., Phase A of all buses).

`x[0, :]:` Extracts the first row (e.g., all phases of Bus 1).

2. **Integer Array Indexing**: This allows you to select non-contiguous elements using other arrays as indices.

* *1D Array x indexed by 1D integer array a:* x[a] returns an array where each element is x[a_i].
* *1D Array x indexed by 2D integer array a:* It returns a 2D array with the shape of a, but with elements taken from x.
* *2D Array x indexed by 1D array a:* x[a] returns the rows specified by the indices in a.
* *2D Array x indexed by two 1D arrays a and b:* x[a, b] returns elements at specific coordinates: (a[0], b[0]), (a[1], b[1])....

3. **Boolean Masking**: If you provide a Boolean vector (an array of True/False) of the same size as your data, NumPy will return only the entries where the value is True.

**Note:** While we can manually create these vectors, the true power of masking comes from Logical Operations (e.g., voltages < 0.95), which we will cover in the upcoming sections.

##### Example 4: Network Data Extraction 

**Scenario:** You have a $3 \times 3$ matrix representing the voltages of 3 buses across 3 time-stamps. You need to extract specific operational data for analysis.

*Task:*
1. Create a $3 \times 3$ matrix V_data with values 1 to 9.
2. Slicing: Extract the last two rows and the last two columns.
3. Negative Index: Access the very last voltage reading in the matrix using negative indices.
4. Integer array Indexing: Use a 1D array rows = [0, 2] and cols = [1, 2] to extract specific coordinates: (0,1) and (2,2).
5. Boolean Mask: Create a manual boolean list mask = [True, False, True] and apply it to the first row of V_data.

In [8]:
V_data = np.arange(1, 10).reshape(3, 3)
print("Original Matrix:\n", V_data)

# Step 1: Slice last 2 rows and last 2 columns
v_slice = ...

# Step 2: Access last element using negative indexing
last_val = ...

# Step 3: Fancy Indexing
# Extract V_data[0,1] and V_data[2,2]
rows = np.array([0, 2])
cols = np.array([1, 2])
selected_points = ...

# Step 4: Boolean Masking
mask = np.array([True, False, True])
masked_row = ... # Apply mask to the first row (V_data[0, :])

print("\nSliced Data:\n", v_slice)
print("\nLast Value:", last_val)
print("\nSelected Coordinates:", selected_points)
print("\nMasked Row:", masked_row)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Sliced Data:
 Ellipsis

Last Value: Ellipsis

Selected Coordinates: Ellipsis

Masked Row: Ellipsis


---
### Basic Array Operations

For this section, we assume that both operands have the same shape. If they do not, NumPy uses a logic called Broadcasting, which we will explore later.

#### A. Element-wise Arithmetic

These operations are applied to each corresponding element in the arrays.
| Operation        | Syntax                          | Description                                      |
|------------------|---------------------------------|--------------------------------------------------|
| Addition         | `x + y` or `np.add(x, y)`       | Sum of corresponding elements.                   |
| Subtraction      | `x - y` or `np.subtract(x, y)`  | Difference of elements.                          |
| Multiplication   | `x * y` or `np.multiply(x, y)`  | Element-wise product (NOT matrix multiplication).|
| Division         | `x / y` or `np.divide(x, y)`    | Quotient of elements.                            |
| Exponentiation   | `x ** n` or `np.power(x, n)`    | Raises elements of x to the power n.             |

#### B. Mathematical and Trigonometric Functions

These functions are essential for converting between Rectangular ($R+jX$) and Polar ($V \angle \theta$) coordinates.
| Category         | Functions                                      | Notes                                                       |
|------------------|-----------------------------------------------|------------------------------------------------------------|
| Trigonometric    | `np.sin()`, `np.cos()`, `np.tan()`            | Inputs must be in radians.                                 |
| Inverse Trig     | `np.arcsin()`, `np.arccos()`, `np.arctan()`   | Returns values in radians.                                 |
| Trig (Advanced)  | `np.arctan2(y, x)`                            | Returns the angle considering the quadrant (useful for phase angles). |
| Exponents/Logs   | `np.exp()`, `np.log()`, `np.log10()`, `np.log2()` | `np.log()` is the natural logarithm (ln).                 |
| Misc             | `np.sqrt()`, `np.abs()`                       | Square root and absolute value (magnitude).                |

#### C. Statistical and Aggregate Functions
These functions reduce an array to a single value (or a smaller array).
| Function | Description |
|----------|------------|
| `np.min()`, `np.max()` | Returns the overall minimum or maximum value of an array. |
| `np.argmin()`, `np.argmax()` | Returns the index of the minimum or maximum value. |
| `np.mean()`, `np.median()`, `np.std()`, `np.var()` | Computes basic statistical measures (mean, median, standard deviation, variance). |
| `np.percentile(x, q)` | Computes the q-th percentile of the data. |
| `np.maximum(x, y)` vs `np.max()` | `np.maximum(x, y)` performs element-wise comparison between two arrays and returns the larger value at each position, whereas `np.max()` returns a single largest value from one array. |

#### D. Working with Axes in 2D Arrays
In a 2D matrix (like a load profile where rows = hours and columns = buses), you often need to calculate statistics for specific directions using the axis parameter.

* `axis = 0 `: Operate down the rows (column-wise result)
* `axis = 1 `: operate across the columns (row-wise result)

##### Example 5: Load Profile Analysis
**Scenario:** You have a $4 \times 3$ matrix representing the Power Load (MW) of 3 different buses over 4 hours.

*Task:*
1. Calculate the total load at each hour (Sum across columns).
2. Find the maximum load encountered by each bus (Max across rows).
3. Find the index (hour) at which the peak load occurred for the first bus.
4. Convert the load from MW to pu (assume $S_{base} = 100$ MW) using element-wise division.
5. Use `np.maximum` to compare the load matrix with a "Safe Limit" array and identify violations.

In [12]:
import numpy as np

# Load Data (Hours x Buses)
load_mw = np.array([
    [120, 150, 80],
    [130, 160, 90],
    [110, 140, 70],
    [150, 170, 100]
])

# Step 1: Total load per hour (axis=1)
hourly_total = ...

# Step 2: Peak load per bus (axis=0)
bus_peaks = ...

# Step 3: Hour index of peak load for Bus 0
peak_hour_bus0 = ...

# Step 4: Convert to pu (Element-wise)
load_pu = ...

# Step 5: Element-wise comparison with a threshold
threshold = 145
violations = np.maximum(load_mw, threshold)

print("Hourly Totals:", hourly_total)
print("Bus Peak Loads:", bus_peaks)
print("Peak Hour Index (Bus 0):", peak_hour_bus0)
print("\nViolations Check (Values capped at threshold):\n", violations)

Hourly Totals: Ellipsis
Bus Peak Loads: Ellipsis
Peak Hour Index (Bus 0): Ellipsis

Violations Check (Values capped at threshold):
 [[145 150 145]
 [145 160 145]
 [145 145 145]
 [150 170 145]]


---
### Logical Operations and Conditions
When you apply a comparison operator to a NumPy array, it doesn't return a single value; it performs an element-wise comparison and returns a Boolean Array (an array of `True` and `False`).

#### A. Basic Comparisons

If x is an array and y is a another array (of same shape), the following comparison operations can be performed. `x > y`, `x < y`, `x == y`, `x != y` The result is a Boolean array of the same shape as `x`.

#### B. Combining Logical Expressions
To combine multiple conditions (e.g., checking if a voltage is between $0.95$ and $1.05$ pu), you must follow two strict rules:
1. Use Parentheses: Each individual condition must be enclosed in ().
2. Use Bitwise Operators: Use the following symbols instead of the words `and`/`or`:
   * & (AND): True if both conditions are True.
   * | (OR): True if at least one condition is True.
   * ~ (NOT): Reverses the Boolean values.
   * ^ (XOR): True if exactly one condition is True.

**Syntax Example:** mask = (voltages > 0.95) & (voltages < 1.05)

#### C. Aggregate Logic: np.any() and np.all()
Sometimes you don't want the full boolean array; you just want a single "Yes/No" answer for the whole system:
* `np.any(condition)`: Returns True if at least one element in the array meets the condition. (e.g., "Is any bus currently in a fault state?")
* `np.all(condition)`: Returns True only if every single element meets the condition. (e.g., "Are all buses within stable frequency limits?")

##### Example 6 Fault Detection System

**Scenario:** You have a 1D array of 6 bus voltages (in pu). You need to write a script that automatically flags safety violations and determines the status of the substation.

*Task:*
1. Define an array v_bus with values: [1.02, 0.88, 1.05, 1.12, 0.98, 0.92].
2. Comparison: Create a boolean mask low_v for buses where voltage is below $0.95$ pu.
3. Combination: Create a boolean mask unstable for buses where voltage is EITHER below $0.90$ pu OR above $1.10$ pu.
4. Aggregate Logic: Use np.any to check if there are any unstable buses.
5. Aggregate Logic: Use np.all to check if all buses are above $0.85$ pu (Critical limit).
6. Extraction: Use the unstable mask as an index for v_bus to print the actual voltage values of the failing buses.

In [ ]:
v_bus = np.array([1.02, 0.88, 1.05, 1.12, 0.98, 0.92])

# Step 1: Flag buses < 0.95
low_v = ...

# Step 2: Flag buses < 0.90 OR > 1.10
# Hint: (cond1) | (cond2)
unstable = ...

# Step 3: Is there ANY instability in the system?
any_unstable = ...

# Step 4: Are ALL buses above the critical 0.85 limit?
system_safe = ...

# Step 5: Extract the values of the unstable voltages
unstable_values = ...

print("Buses with Low Voltage Mask:", low_v)
print("Any Unstable Buses?", any_unstable)
print("System Critical Safety Check (All > 0.85):", system_safe)
print("Actual Unstable Voltages:", unstable_values)